# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/SWE-Tutorial-8',
                'doc_host': 'https://ajsass.github.io',
                'git_url': 'https://github.com/ajsass/SWE-Tutorial-8',
                'lib_path': 'SWE_Tutorial_8'},
  'syms': {'SWE_Tutorial_8.core': {'SWE_Tutorial_8.core.foo': ('core.html#foo', 'SWE_Tutorial_8/core.py')}}}